const ROOT_CONTEXT = 'GameEngine';

const WINDOW_WIDTH = 1280;
const WINDOW_HEIGHT = 750;

const WINDOW_WIDTH_PX = `${WINDOW_WIDTH}px`;
const WINDOW_HEIGHT_PX = `${WINDOW_HEIGHT}px`;

module.exports = {
  ROOT_CONTEXT,
  WINDOW_WIDTH,
  WINDOW_HEIGHT,
  WINDOW_WIDTH_PX,
  WINDOW_HEIGHT_PX
};
